export default {
	en: {
		gp_title: 'Google Play',
		play_pass: 'Play Pass',
		play_points: 'Play Points',
		gift_cards: 'Gift cards',
		redeem: 'Redeem',
		refund_policy: 'Refund policy',
		kids_family: 'Kids & family',
		parent_guide: 'Parent Guide',
		family_sharing: 'Family sharing',
		terms_of_service: 'Terms of Service',
		privacy: 'Privacy',
		about_google_play: 'About Google Play',
		developers: 'Developers',
		google_store: 'Google Store',
		vat: 'All prices include VAT.'
	},
	es: {
		gp_title: 'Google Play',
		play_pass: 'Play Pass',
		play_points: 'Play Points',
		gift_cards: 'Tarjetas regalo',
		redeem: 'Canjear',
		refund_policy: 'Política de reembolsos',
		kids_family: 'Niños y familia',
		parent_guide: 'Guía para padres',
		family_sharing: 'Compartir en familia',
		terms_of_service: 'Términos del Servicio',
		privacy: 'Privacidad',
		about_google_play: 'Información sobre Google Play',
		developers: 'Desarrolladores',
		google_store: 'Google Store',
		vat: 'Todos los precios incluyen IVA'
	},
	pt: {
		gp_title: 'Google Play',
		play_pass: 'Play Pass',
		play_points: 'Play Points',
		gift_cards: 'Vales-presente',
		redeem: 'Resgatar',
		refund_policy: 'Política de reembolso',
		kids_family: 'Crianças e família',
		parent_guide: 'Guia para a família',
		family_sharing: 'Compartilhamento em família',
		terms_of_service: 'Termos de Serviço',
		privacy: 'Privacidade',
		about_google_play: 'Sobre o Google Play',
		developers: 'Desenvolvedores',
		google_store: 'Google Store',
		vat: 'Todos os preços incluem Tributo.'
	},
	th: {
		gp_title: 'Google Play',
		play_pass: 'Play Pass',
		play_points: 'Play Points',
		gift_cards: 'บัตรของขวัญ',
		redeem: 'แลก',
		refund_policy: 'นโยบายการคืนเงิน',
		kids_family: 'เด็กและครอบครัว',
		parent_guide: 'คำแนะนำสำหรับผู้ปกครอง',
		family_sharing: 'การแชร์ในครอบครัว',
		terms_of_service: 'ข้อกำหนดในการให้บริการ',
		privacy: 'ความเป็นส่วนตัว',
		about_google_play: 'เกี่ยวกับ Google Play',
		developers: 'นักพัฒนาแอป',
		google_store: 'Google Store',
		vat: 'ราคาทั้งหมดรวม VAT'
	},
	my: {
		gp_title: 'Google Play',
		play_pass: 'Play Pass',
		play_points: 'Play Points',
		gift_cards: 'Kad hadiah',
		redeem: 'Tebus',
		refund_policy: 'Dasar pembayaran balik',
		kids_family: 'Kanak-kanak & keluarga',
		parent_guide: 'Panduan Ibu Bapa',
		family_sharing: 'Perkongsian keluarga',
		terms_of_service: 'Syarat Perkhidmatan',
		privacy: 'Privasi',
		about_google_play: 'Perihal Google Play',
		developers: 'Pembangun',
		google_store: 'Google Store',
		vat: 'Semua harga termasuk VAT.'
	},
	vi: {
		gp_title: 'Google Play',
		play_pass: 'Play Pass',
		play_points: 'Play Points',
		gift_cards: 'Thẻ Google Play',
		redeem: 'Đổi phần thưởng',
		refund_policy: 'Chính sách hoàn tiền',
		kids_family: 'Trẻ em và gia đình',
		parent_guide: 'Hướng dẫn dành cho cha mẹ',
		family_sharing: 'Chia sẻ với gia đình',
		terms_of_service: 'Điều khoản dịch vụ',
		privacy: 'Quyền riêng tư',
		about_google_play: 'Giới thiệu về Google Play',
		developers: 'Nhà phát triển',
		google_store: 'Google Store',
		vat: 'Mọi mức giá đều bao gồm thuế VAT.'
	}
};
